### ISSUE TITLE
Found an error that tsd does not currently support (ts2353)

### ISSUE THREAD

**Issue by UziTech** [tsdjs/tsd#201]
Got this error after updating to 0.30.0:

https://github.com/UziTech/marked-emoji/actions/runs/7243096934/job/19729425819?pr=207

Error thrown here:

https://github.com/UziTech/marked-emoji/blob/main/types_test/index.test-d.ts#L7

**Comment by Mister-Hope** [comment]
I also encountered this problem when upgrading to new version.

Hope tsd can support this issue detecting soon "Object literal may only specify known properties, and custom does not exist in type xxx."

**Comment by manudeli** [comment]
Same problem I met
